-- =========================================================
-- VIBE RPA 교육기업 시장 반응 분석 대시보드 - Supabase Schema
-- =========================================================

-- 본 시스템은 기본적으로 Supabase의 public.todos 테이블을 활용하여
-- 기업별 요약 데이터(RPA_SUMMARY) 및 수집 기사(RPA_ARTICLE)를 즉시 실시간 동기화합니다.
-- 추가로 전용 테이블을 분리하여 사용하고자 할 경우 아래 쿼리를 SQL Editor에서 실행할 수 있습니다.

CREATE TABLE IF NOT EXISTS public.market_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company TEXT NOT NULL,
    positive INT DEFAULT 0,
    negative INT DEFAULT 0,
    total INT DEFAULT 0,
    ratio FLOAT DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.cafe_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    sentiment TEXT DEFAULT '중립',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS 활성화 및 공개 정책
ALTER TABLE public.market_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cafe_articles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public all access on market_summary" ON public.market_summary;
CREATE POLICY "Allow public all access on market_summary" ON public.market_summary
FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all access on cafe_articles" ON public.cafe_articles;
CREATE POLICY "Allow public all access on cafe_articles" ON public.cafe_articles
FOR ALL USING (true) WITH CHECK (true);
