-- =========================================================
-- TaskFlow To-Do App - Supabase PostgreSQL Table Schema
-- =========================================================

-- 1. Create todos table
CREATE TABLE IF NOT EXISTS public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    category TEXT DEFAULT '업무',
    priority TEXT DEFAULT '보통',
    due_date TEXT DEFAULT '',
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow all operations (Insert, Select, Update, Delete) with anon/public key
DROP POLICY IF EXISTS "Allow public all access" ON public.todos;
CREATE POLICY "Allow public all access" ON public.todos
FOR ALL
USING (true)
WITH CHECK (true);

-- 4. Sample Seed Tasks (Optional)
INSERT INTO public.todos (title, description, category, priority, due_date, completed)
VALUES 
  ('파이썬 업무자동화 강의 복습하기', '실습 파일 확인 및 Jupyter Notebook 코드 정리', '공부', '높음', CURRENT_DATE::text, false),
  ('Flask 할 일 관리 웹앱 완성하기', 'REST API 및 스타일리시한 다크모드 UI 구현', '업무', '높음', CURRENT_DATE::text, true),
  ('장보기 목록 작성 및 마트 가기', '원두커피, 우유, 신선한 과일 구매', '쇼핑', '보통', CURRENT_DATE::text, false),
  ('주말 운동 루틴 계획하기', '유산소 30분 + 스트레칭 20분', '개인', '낮음', '', false)
ON CONFLICT DO NOTHING;
